[build]
  base = "web"
  command = "npm install && npm --prefix ../backend install && npm run build"
  publish = "web/dist"
  functions = "../backend/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
